### PR TITLE
Add all new images

### PR DESCRIPTION
**Pull request by kaxil**
Added the following images:

- 1.10.10-1
- 1.10.10-2
- 1.10.7-12
- 1.10.10-3
- 1.10.7-13

### CODE REVIEW

**Comment by kaxil** [comment]
I think this can be merged now

**Comment by kaxil** [comment]
@sjmiller609 https://github.com/astronomer/google-environments/pull/66 is merged but that commit on master still hasn't completed the CI (https://app.circleci.com/pipelines/github/astronomer/google-environments/134/workflows/20406e99-2e12-42e5-b819-857316743ae9).

So it looks like it hasn't been pushed to Prod, whats the ETA on that ?

**Comment by kaxil** [comment]
ping @sjmiller609 @schnie

**Comment by schnie** [comment]
@sjmiller609 has that google-environments commit been shipped?

**Comment by sjmiller609** [comment]
> @sjmiller609 has that google-environments commit been shipped?

This can be checked in each environment using "helm get values astronomer"

**Comment by kaxil** [comment]
Yeah, I don't think it has been shipped.

The CI still says on "HOLD" (https://app.circleci.com/pipelines/github/astronomer/google-environments/134/workflows/20406e99-2e12-42e5-b819-857316743ae9)

https://github.com/astronomer/google-environments/commits/master

**Comment by sjmiller609** [comment]
To ship to prod, assuming it is not already shipped, it is just a button click away. but IIRC, there is a hotfix on prod we want to avoid clobbering. @jpweber is the release commander for 0.16, and he provided the hotfix. Jim are we ready to ship this reconfiguration?

**Comment by jpweber** [comment]
The only "hot fix" on prod that I'm aware of was psp related. it is in the release-0.16 branch so any next version would pick it up. But I can also re-apply real fast after we deploy as long as I know its going on. I'm not aware of any other outstanding changes that would be clobbered. So I'm ok with this.

**Comment by sjmiller609** [comment]
@jpweber thank you, will you please publish the new patch version and ship it along with these reconfigurations to staging, ask here for confirmation, then production? I am happy to help

**Comment by jpweber** [comment]
I'm in the middle of some other work, if this is urgent I would appreciate it if you do it. If this is not urgent then I can go over it with Daniel this afternoon so he can see the process.

**Comment by vishwas-astro** [comment]
@sjmiller609 @jpweber @schnie can we ship the change here: https://github.com/astronomer/google-environments/pull/66 with the other 0.16 patch we are planning to ship this week with Houston and Astro UI bug fixes? 

@kaxil @ashb it will be great if we can tag some of these changes/PRs with specific milestones so they don't slip through the cracks and we can track them as we release to cloud.

**Comment by kaxil** [comment]
> @sjmiller609 @jpweber @schnie can we ship the change here: [astronomer/google-environments#66](https://github.com/astronomer/google-environments/pull/66) with the other 0.16 patch we are planning to ship this week with Houston and Astro UI bug fixes?
> 
> @kaxil @ashb it will be great if we can tag some of these changes/PRs with specific milestones so they don't slip through the cracks and we can track them as we release to cloud.

Sure happy to add milestones or labels whatever you guys are using for tracking. Can you let me know what you guys use or an example PR where I can look for the labels/  milestone

**Comment by jpweber** [comment]
I'm ok shipping patch updates today to stage and prod if all looks good. We just need to coordinate what all is going in it. @vishwas-astro is that something we can do on the release standup today, or should we chat before hand to get it out sooner?

**Comment by ashb** [comment]
> @kaxil @ashb it will be great if we can tag some of these changes/PRs with specific milestones so they don't slip through the cracks and we can track them as we release to cloud.

Do you mean putting a label on https://github.com/astronomer/google-environments/pull/66, for instance? Which label should we use given that changes like this happen independently to a release

**Comment by kaxil** [comment]
@ashb Can you merge this one ( I don't have permissions)

**Pull request merged**
